In [1]:
import pandas as pd
import os

In [2]:
events=pd.read_json("../../simulation.jsonlines", orient="records",lines=True)
planes=pd.read_json("../../plans.jsonlines", orient="records",lines=True)
positions = pd.read_json("../../positions.jsonlines", orient="records", lines=True)

## LIMPIEZA

In [3]:
events = events.drop_duplicates()

In [25]:
events

,eventDescription,eventTime,eventType,simulationId,truckId
0,"(plaza del Dos de Mayo, 6, Madrid, [-3.7041862...",5760,Truck departed,a2bfd344-3b14-462a-82e7-d42aca54a650,1669HSZ
1,"(plaza del Dos de Mayo, 6, Madrid, [-3.7041862...",5730,Truck departed,a2bfd344-3b14-462a-82e7-d42aca54a650,8809GPH
2,"(plaza del Dos de Mayo, 6, Madrid, [-3.7041862...",5730,Truck departed,a2bfd344-3b14-462a-82e7-d42aca54a650,1161GJN
3,"(plaza del Dos de Mayo, 6, Madrid, [-3.7041862...",5430,Truck departed,a2bfd344-3b14-462a-82e7-d42aca54a650,3321FBL
4,"(plaza del Dos de Mayo, 6, Madrid, [-3.7041862...",5310,Truck departed,a2bfd344-3b14-462a-82e7-d42aca54a650,2423VRT
...,...,...,...,...,...
26577,"(calle de Juan de Austria, 1, Madrid, [-3.6991...",11562780,Truck arrived,f0f90050-5a0f-4965-864e-d6bc0d02b5a0,8386WZB
26578,"Packet 83 to (calle de Juan de Austria, 1, Mad...",11623380,Truck ended delivering,f0f90050-5a0f-4965-864e-d6bc0d02b5a0,8386WZB
26579,"(plaza del Dos de Mayo, 6, Madrid, [-3.7041862...",11623470,Truck departed to depot,f0f90050-5a0f-4965-864e-d6bc0d02b5a0,8386WZB
26580,,11813550,Truck ended route,f0f90050-5a0f-4965-864e-d6bc0d02b5a0,8386WZB
26581,,12553080,Truck ended route,f0f90050-5a0f-4965-864e-d6bc0d02b5a0,5030LXK

In [101]:
positions.drop_duplicates()

TypeError: unhashable type: 'dict'

In [4]:
planes

,items,simulationId,trucks
0,"[{'itemId': '0', 'locationId': '326ae8dc7810de...",a2bfd344-3b14-462a-82e7-d42aca54a650,"[{'items': ['23', '24', '4', '25', '26', '27',..."
1,"[{'itemId': '0', 'locationId': '271c4e156a04e8...",a8a11526-6b9b-4143-bfb1-ffcae600a17e,"[{'items': ['62', '63', '69', '70', '71', '21'..."
2,"[{'itemId': '0', 'locationId': '6aa95e84c67637...",2f956e3a-25df-4c5e-bb50-92d92dc9ba00,"[{'items': ['79', '20', '21', '5', '76', '59',..."
3,"[{'itemId': '0', 'locationId': '0078f3bf6db092...",45c9a42a-7cb5-4266-b0aa-a05b3f446390,"[{'items': ['3', '4', '5', '6', '72', '11', '1..."
4,"[{'itemId': '0', 'locationId': '92e059821c9ca8...",864bd9f3-074d-45e8-a032-5a01237ae290,"[{'items': ['77', '78', '79', '16', '17', '91'..."
...,...,...,...
94,"[{'itemId': '0', 'locationId': '281ec8ac82cccd...",81acb266-ab82-497b-92d9-fae490cc4823,"[{'items': ['36', '37', '49', '6', '7', '8', '..."
95,"[{'itemId': '0', 'locationId': '950001b613cb58...",f007019f-866d-48be-a0cb-bd96328ee43b,"[{'items': ['46', '47', '48', '49', '40', '24'..."
96,"[{'itemId': '0', 'locationId': 'b40599012e4fba...",f0f90050-5a0f-4965-864e-d6bc0d02b5a0,"[{'items': ['16', '17', '42', '43', '44', '45'..."
97,"[{'itemId': '0', 'locationId': '074dc13529fd8b...",e33505ca-bfdb-496f-bcfd-b8b913a42637,"[{'items': ['62', '63', '64', '86', '10', '11'..."
98,"[{'itemId': '0', 'locationId': 'd1214b27823e6d...",6deec7b7-6c11-418c-a1bd-f99a9e3261b6,"[{'items': ['53', '54', '55', '83', '84', '85'..."

## Tiempos de entrega

In [6]:
entregas = events[events.eventType.isin(["Truck ended delivering", "Truck started delivering"])]
entregas = entregas.sort_values("eventType",ascending=True)
entregas = entregas.sort_values(by=["simulationId", "truckId", "eventTime"])

In [7]:
entregas["deliverTime"] = entregas["eventTime"].diff()
entregas = entregas[entregas.eventType == "Truck ended delivering"]
entregas

,eventDescription,eventTime,eventType,simulationId,truckId,deliverTime
13021,"Packet 78 to (calle del Poeta Blas de Otero, 2...",872250,Truck ended delivering,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,120630.0
13112,"Packet 79 to (calle del Poeta Blas de Otero, 2...",992820,Truck ended delivering,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,120570.0
13566,"Packet 50 to (calle de Valdecanillas, 59, Madr...",1536120,Truck ended delivering,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,60600.0
13614,"Packet 51 to (calle de Valdecanillas, 59, Madr...",1596720,Truck ended delivering,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,60600.0
13666,"Packet 52 to (calle de Valdecanillas, 59, Madr...",1657320,Truck ended delivering,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,60600.0
...,...,...,...,...,...,...
11113,"Packet 42 to (calle de la Comunidad de Madrid,...",7565580,Truck ended delivering,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,60600.0
11176,"Packet 43 to (calle de la Comunidad de Madrid,...",7626180,Truck ended delivering,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,60570.0
11655,"Packet 79 to (calle San AndrÃ©s, 21, Majadahond...",8243580,Truck ended delivering,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,60600.0
11729,"Packet 80 to (calle San AndrÃ©s, 21, Majadahond...",8304180,Truck ended delivering,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,60600.0
11786,"Packet 81 to (calle San AndrÃ©s, 21, Majadahond...",8364780,Truck ended delivering,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,60600.0

In [8]:
events["eventType"].value_counts()

Truck started delivering    8567
Truck ended delivering      8567
Truck departed              3444
Truck arrived               3444
Truck initialized            640
Truck received packets       640
Truck departed to depot      640
Truck ended route            640
Name: eventType, dtype: int64

## Desanidar los planes

In [9]:
planes

,items,simulationId,trucks
0,"[{'itemId': '0', 'locationId': '326ae8dc7810de...",a2bfd344-3b14-462a-82e7-d42aca54a650,"[{'items': ['23', '24', '4', '25', '26', '27',..."
1,"[{'itemId': '0', 'locationId': '271c4e156a04e8...",a8a11526-6b9b-4143-bfb1-ffcae600a17e,"[{'items': ['62', '63', '69', '70', '71', '21'..."
2,"[{'itemId': '0', 'locationId': '6aa95e84c67637...",2f956e3a-25df-4c5e-bb50-92d92dc9ba00,"[{'items': ['79', '20', '21', '5', '76', '59',..."
3,"[{'itemId': '0', 'locationId': '0078f3bf6db092...",45c9a42a-7cb5-4266-b0aa-a05b3f446390,"[{'items': ['3', '4', '5', '6', '72', '11', '1..."
4,"[{'itemId': '0', 'locationId': '92e059821c9ca8...",864bd9f3-074d-45e8-a032-5a01237ae290,"[{'items': ['77', '78', '79', '16', '17', '91'..."
...,...,...,...
94,"[{'itemId': '0', 'locationId': '281ec8ac82cccd...",81acb266-ab82-497b-92d9-fae490cc4823,"[{'items': ['36', '37', '49', '6', '7', '8', '..."
95,"[{'itemId': '0', 'locationId': '950001b613cb58...",f007019f-866d-48be-a0cb-bd96328ee43b,"[{'items': ['46', '47', '48', '49', '40', '24'..."
96,"[{'itemId': '0', 'locationId': 'b40599012e4fba...",f0f90050-5a0f-4965-864e-d6bc0d02b5a0,"[{'items': ['16', '17', '42', '43', '44', '45'..."
97,"[{'itemId': '0', 'locationId': '074dc13529fd8b...",e33505ca-bfdb-496f-bcfd-b8b913a42637,"[{'items': ['62', '63', '64', '86', '10', '11'..."
98,"[{'itemId': '0', 'locationId': 'd1214b27823e6d...",6deec7b7-6c11-418c-a1bd-f99a9e3261b6,"[{'items': ['53', '54', '55', '83', '84', '85'..."

In [10]:
pd.DataFrame(planes.trucks[0])

,items,route,truck_id
0,"[23, 24, 4, 25, 26, 27, 28, 40, 41, 42, 43, 13...","[{'destination': 'af3ea5c0e98151a51bd39c64', '...",5534TPH
1,"[74, 75, 76, 67, 68, 69, 70, 92, 93, 94, 55, 5...","[{'destination': 'faf06210580833f8c7963506', '...",2423VRT
2,"[18, 19, 57, 58, 88, 89, 90, 91, 54, 20, 21, 2...","[{'destination': 'bef2df0471ee1c26b4ab6ba9', '...",0265TYL
3,"[87, 0, 1, 2, 3, 33, 95, 96, 97]","[{'destination': '7a249403ad22a72495769f75', '...",8809GPH
4,"[31, 32, 37, 38, 39, 66]","[{'destination': '1e38734ff239ccf75bf04b95', '...",1161GJN
5,[86],"[{'destination': '7d1544d169eeeb1d917e9f02', '...",1669HSZ
6,"[77, 78, 79, 52, 53, 29, 30, 80, 81, 82, 34, 3...","[{'destination': '166c008321c564cf6c885cb2', '...",3321FBL

In [11]:
pd.DataFrame(pd.DataFrame(planes.trucks[0]).route[0])

                destination  duration                    origin
0  af3ea5c0e98151a51bd39c64       197  ce6feed06bc1a9e5aff95f04
1  c0430d1e19c34a06e343a270       733  af3ea5c0e98151a51bd39c64
2  b31f6bb5c55435cb5495a62b       380  c0430d1e19c34a06e343a270
3  58a50ddf91095c052e330fd6       612  b31f6bb5c55435cb5495a62b
4  910cd4ad38bc68ff7abdd941       850  58a50ddf91095c052e330fd6
5  49a09d201cc830dc1c4e87fc       241  910cd4ad38bc68ff7abdd941
6  324beca4107779629830c6d3       689  49a09d201cc830dc1c4e87fc
7  123039c250dd5a3e7c3e4fc8       187  324beca4107779629830c6d3
8  5a13a4517d5fc3018de2dbea      1203  123039c250dd5a3e7c3e4fc8
9  ce6feed06bc1a9e5aff95f04        99  5a13a4517d5fc3018de2dbea

In [12]:
planes_desanidado = planes.join(planes.trucks.explode().apply(pd.Series), lsuffix='_planes').reset_index(drop=True)
planes_desanidado

,items_planes,simulationId,trucks,items,route,truck_id
0,"[{'itemId': '0', 'locationId': '326ae8dc7810de...",a2bfd344-3b14-462a-82e7-d42aca54a650,"[{'items': ['23', '24', '4', '25', '26', '27',...","[23, 24, 4, 25, 26, 27, 28, 40, 41, 42, 43, 13...","[{'destination': 'af3ea5c0e98151a51bd39c64', '...",5534TPH
1,"[{'itemId': '0', 'locationId': '326ae8dc7810de...",a2bfd344-3b14-462a-82e7-d42aca54a650,"[{'items': ['23', '24', '4', '25', '26', '27',...","[74, 75, 76, 67, 68, 69, 70, 92, 93, 94, 55, 5...","[{'destination': 'faf06210580833f8c7963506', '...",2423VRT
2,"[{'itemId': '0', 'locationId': '326ae8dc7810de...",a2bfd344-3b14-462a-82e7-d42aca54a650,"[{'items': ['23', '24', '4', '25', '26', '27',...","[18, 19, 57, 58, 88, 89, 90, 91, 54, 20, 21, 2...","[{'destination': 'bef2df0471ee1c26b4ab6ba9', '...",0265TYL
3,"[{'itemId': '0', 'locationId': '326ae8dc7810de...",a2bfd344-3b14-462a-82e7-d42aca54a650,"[{'items': ['23', '24', '4', '25', '26', '27',...","[87, 0, 1, 2, 3, 33, 95, 96, 97]","[{'destination': '7a249403ad22a72495769f75', '...",8809GPH
4,"[{'itemId': '0', 'locationId': '326ae8dc7810de...",a2bfd344-3b14-462a-82e7-d42aca54a650,"[{'items': ['23', '24', '4', '25', '26', '27',...","[31, 32, 37, 38, 39, 66]","[{'destination': '1e38734ff239ccf75bf04b95', '...",1161GJN
...,...,...,...,...,...,...
635,"[{'itemId': '0', 'locationId': 'd1214b27823e6d...",6deec7b7-6c11-418c-a1bd-f99a9e3261b6,"[{'items': ['53', '54', '55', '83', '84', '85'...","[53, 54, 55, 83, 84, 85, 86, 26, 27, 29, 30, 3...","[{'destination': '225cd814768e8ca390983313', '...",5534TPH
636,"[{'itemId': '0', 'locationId': 'd1214b27823e6d...",6deec7b7-6c11-418c-a1bd-f99a9e3261b6,"[{'items': ['53', '54', '55', '83', '84', '85'...","[72, 73, 74, 88, 89, 90, 91, 43, 62, 63, 64, 3...","[{'destination': '417bf3aae83127cd905f3bc9', '...",3953RLD
637,"[{'itemId': '0', 'locationId': 'd1214b27823e6d...",6deec7b7-6c11-418c-a1bd-f99a9e3261b6,"[{'items': ['53', '54', '55', '83', '84', '85'...","[6, 7, 8, 9]","[{'destination': '1e1251e186dd507f63e4d1e6', '...",5030LXK
638,"[{'itemId': '0', 'locationId': 'd1214b27823e6d...",6deec7b7-6c11-418c-a1bd-f99a9e3261b6,"[{'items': ['53', '54', '55', '83', '84', '85'...","[44, 45, 46, 47, 94, 20, 21, 22, 95, 96, 97, 6...","[{'destination': '6a33d0bcd3624ccb86febf09', '...",3321FBL
639,"[{'itemId': '0', 'locationId': 'd1214b27823e6d...",6deec7b7-6c11-418c-a1bd-f99a9e3261b6,"[{'items': ['53', '54', '55', '83', '84', '85'...","[79, 80, 81, 82, 24, 25, 40, 41, 42, 12, 23, 9...","[{'destination': '17c23e21622baec6f08861dd', '...",6270NFM

In [13]:
planes_desanidado_x2 = planes_desanidado.join(planes_desanidado.route.explode().apply(pd.Series)).reset_index(drop=True)
planes_desanidado_x2[['simulationId', 'truck_id', 'origin', 'destination', 'duration']]

,simulationId,truck_id,origin,destination,duration
0,a2bfd344-3b14-462a-82e7-d42aca54a650,5534TPH,ce6feed06bc1a9e5aff95f04,af3ea5c0e98151a51bd39c64,197
1,a2bfd344-3b14-462a-82e7-d42aca54a650,5534TPH,af3ea5c0e98151a51bd39c64,c0430d1e19c34a06e343a270,733
2,a2bfd344-3b14-462a-82e7-d42aca54a650,5534TPH,c0430d1e19c34a06e343a270,b31f6bb5c55435cb5495a62b,380
3,a2bfd344-3b14-462a-82e7-d42aca54a650,5534TPH,b31f6bb5c55435cb5495a62b,58a50ddf91095c052e330fd6,612
4,a2bfd344-3b14-462a-82e7-d42aca54a650,5534TPH,58a50ddf91095c052e330fd6,910cd4ad38bc68ff7abdd941,850
...,...,...,...,...,...
4079,6deec7b7-6c11-418c-a1bd-f99a9e3261b6,6270NFM,20ee036e147b4a1bd5af0e1c,5bec37aee4796cc965e71c88,1173
4080,6deec7b7-6c11-418c-a1bd-f99a9e3261b6,6270NFM,5bec37aee4796cc965e71c88,1f183bd64aa5bfae47843de5,1198
4081,6deec7b7-6c11-418c-a1bd-f99a9e3261b6,6270NFM,1f183bd64aa5bfae47843de5,4551fdc303a5ddafa1dcf28c,1133
4082,6deec7b7-6c11-418c-a1bd-f99a9e3261b6,6270NFM,4551fdc303a5ddafa1dcf28c,2884f6b369dc20f3051a216d,804
4083,6deec7b7-6c11-418c-a1bd-f99a9e3261b6,6270NFM,2884f6b369dc20f3051a216d,ce6feed06bc1a9e5aff95f04,750

In [14]:
planes_desanidado_x2.sort_values(by=["simulationId", "truck_id"], inplace=True)

In [15]:
planes_desanidado_x2

,items_planes,simulationId,trucks,items,route,truck_id,destination,duration,origin
2334,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,2e8d1b7b9fad4f083892d83c,614,ce6feed06bc1a9e5aff95f04
2335,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,f5a3aab0c10fb7c5c60f2b01,397,2e8d1b7b9fad4f083892d83c
2336,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,4b5f692a806a39d1317d15d4,259,f5a3aab0c10fb7c5c60f2b01
2337,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,64bba266de127a5949f52d9a,349,4b5f692a806a39d1317d15d4
2338,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,6942f2624e971761b7dd9208,384,64bba266de127a5949f52d9a
...,...,...,...,...,...,...,...,...,...
1256,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,92e059821c9ca8b3967bece4,157,fb28b93228a49e10f73abd62
1257,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,1f9012c136c055e10f9ef9cb,300,92e059821c9ca8b3967bece4
1258,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,0efbacc39472a86ca3de1b21,2620,1f9012c136c055e10f9ef9cb
1259,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,7658997164924eab18ea6e08,472,0efbacc39472a86ca3de1b21
1260,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,ce6feed06bc1a9e5aff95f04,1322,7658997164924eab18ea6e08

### EDA

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\carlo\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

### Limpieza

In [17]:
# Cargar los archivos JSONLines
events = pd.read_json("../../simulation.jsonlines", orient="records", lines=True)
planes = pd.read_json("../../plans.jsonlines", orient="records", lines=True)
positions = pd.read_json("../../positions.jsonlines", orient="records", lines=True)

In [18]:
# Limpieza de datos: eliminar duplicados y valores nulos
for df in [events, planes, positions]:
    df.drop_duplicates(inplace=True)
    df.dropna(inplace=True)

TypeError: unhashable type: 'list'

In [ ]:
## Eliminar valores nulos
events.dropna(inplace=True)
planes.dropna(inplace=True)
positions.dropna(inplace=True)

In [ ]:
# ConversiÃ³n de tipos de datos
if "eventTime" in events.columns:
    events["eventTime"] = pd.to_numeric(events["eventTime"], errors='coerce')

In [ ]:
# AnÃ¡lisis exploratorio de datos (EDA)
print("Resumen estadÃ­stico de eventos:")
print(events.describe())
print("\nResumen estadÃ­stico de planes:")
print(planes_desanidado_x2.describe())
print("\nResumen estadÃ­stico de posiciones:")
print(positions.describe())

In [ ]:
# VisualizaciÃ³n de distribuciones clave
plt.figure(figsize=(10,5))
sns.histplot(planes_desanidado_x2['duration'], bins=20, kde=True)
plt.title("DistribuciÃ³n del tiempo de viaje")
plt.xlabel("Tiempo de viaje")
plt.ylabel("Frecuencia")
plt.show()

In [ ]:
plt.figure(figsize=(10,5))
sns.histplot(entregas['deliverTime'], bins=20, kde=True)
plt.title("DistribuciÃ³n del tiempo de entrega")
plt.xlabel("Tiempo de entrega")
plt.ylabel("Frecuencia")
plt.show()

In [ ]:
## Convertir tipos de datos si es necesario
if 'tiempo_viaje' in planes.columns:
    planes['tiempo_viaje'] = pd.to_numeric(plan['tiempo_viaje'], errors='coerce')
if 'tiempo_entrega' in planes.columns:
    planes['tiempo_entrega'] = pd.to_numeric(plan['tiempo_entrega'], errors='coerce')

In [ ]:
# AnÃ¡lisis de correlaciones
correlation_matrix = planes_desanidado_x2.corr()
plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de Correlaciones")
plt.show()

In [ ]:
# NÃºmero de paquetes recibidos por cada localizaciÃ³n
if "destination" in planes_desanidado_x2.columns:
    paquetes_por_localizacion = planes_desanidado_x2.groupby('destination')['truck_id'].count()
    print("\nNÃºmero de paquetes recibidos por cada localizaciÃ³n:")
    print(paquetes_por_localizacion)
else:
    print("Error: 'destination' no encontrada en planes_desanidado_x2.")

In [ ]:
# NÃºmero de paquetes transportados en total por cada camiÃ³n
if "truck_id" in planes_desanidado_x2.columns:
    paquetes_por_camion = planes_desanidado_x2.groupby('truck_id')['destination'].count()
    print("\nNÃºmero de paquetes transportados en total por cada camiÃ³n:")
    print(paquetes_por_camion)
else:
    print("Error: 'truck_id' no encontrada en planes_desanidado_x2.")

In [ ]:
# NÃºmero de localizaciones distintas visitadas por cada camiÃ³n
locaciones_por_camion = planes_desanidado_x2.groupby('truck_id')['destination'].nunique()
print("\nNÃºmero de localizaciones distintas visitadas por cada camiÃ³n:")
print(locaciones_por_camion)

In [ ]:
# DistribuciÃ³n del nÃºmero de eventos de cada tipo
if "eventType" in events.columns:
    eventos_distribucion = events['eventType'].value_counts()
    print("\nDistribuciÃ³n del nÃºmero de eventos de cada tipo:")
    print(eventos_distribucion)
else:
    print("Error: 'eventType' no encontrada en events.")

In [ ]:
# NÃºmero de paquetes que lleva cada camiÃ³n en cada viaje
if "simulationId" in planes_desanidado_x2.columns:
    paquetes_por_viaje = planes_desanidado_x2.groupby(['truck_id', 'simulationId'])['destination'].count()
    print("\nNÃºmero de paquetes que lleva cada camiÃ³n en cada viaje:")
    print(paquetes_por_viaje)
else:
    print("Error: 'simulationId' no encontrada en planes_desanidado_x2.")

In [ ]:
print("Resumen estadÃ­stico de las duraciones de viaje:")
print(planes_desanidado_x2['duration'].describe())

In [ ]:
# VisualizaciÃ³n de distribuciones
plt.figure(figsize=(10,5))
sns.histplot(planes_desanidado_x2['duration'], bins=20, kde=True)
plt.title("DistribuciÃ³n del tiempo de viaje")
plt.xlabel("DuraciÃ³n")
plt.ylabel("Frecuencia")
plt.show()

In [19]:
plt.figure(figsize=(10,5))
sns.histplot(planes_desanidado_x2['tiempo_entrega'], bins=20, kde=True)
plt.title("DistribuciÃ³n del tiempo de entrega")
plt.xlabel("Tiempo de entrega")
plt.ylabel("Frecuencia")
plt.show()

KeyError: 'tiempo_entrega'

In [ ]:
# LocalizaciÃ³n mÃ¡s visitada
loc_mas_visitada = events['location'].value_counts().idxmax()
print(f"La localizaciÃ³n mÃ¡s visitada es: {loc_mas_visitada}")

In [ ]:
# AnÃ¡lisis de correlaciones
correlation_matrix = planes_desanidado_x2.corr()
plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de Correlaciones")
plt.show()

In [ ]:
# NÃºmero de paquetes recibidos por cada localizaciÃ³n
paquetes_por_localizacion = planes_desanidado.groupby('destination')['packages'].sum()
print("\nNÃºmero de paquetes recibidos por cada localizaciÃ³n:")
print(paquetes_por_localizacion)

In [ ]:

# NÃºmero de paquetes transportados en total por cada camiÃ³n
paquetes_por_camion = planes_desanidado.groupby('truck_id')['packages'].sum()
print("\nNÃºmero de paquetes transportados en total por cada camiÃ³n:")
print(paquetes_por_camion)

In [ ]:
# NÃºmero de localizaciones distintas visitadas por cada camiÃ³n
locaciones_por_camion = planes_desanidado_x2.groupby('truck_id')['destination'].nunique()
print("\nNÃºmero de localizaciones distintas visitadas por cada camiÃ³n:")
print(locaciones_por_camion)

In [20]:
# DistribuciÃ³n del nÃºmero de eventos de cada tipo
eventos_distribucion = events['eventType'].value_counts()
print("\nDistribuciÃ³n del nÃºmero de eventos de cada tipo:")
print(eventos_distribucion)

DistribuciÃ³n del nÃºmero de eventos de cada tipo:
Truck started delivering    8567
Truck ended delivering      8567
Truck departed              3444
Truck arrived               3444
Truck initialized            640
Truck received packets       640
Truck departed to depot      640
Truck ended route            640
Name: eventType, dtype: int64

In [22]:
### NÃºmero de paquetes que lleva cada camiÃ³n en cada viaje
paquetes_por_viaje = planes_desanidado_x2.groupby(['truck_id', 'destination'])['packages'].sum()
print("\nNÃºmero de paquetes que lleva cada camiÃ³n en cada viaje:")
print(paquetes_por_viaje)

KeyError: 'Column not found: packages'


### transformacion de los datos
Comenzaremos con lso tiempos de viaje de los camiones

In [38]:
viajes = events[events.eventType.isin(["Truck departed", "Truck arrived"])]

In [39]:


viajes = viajes.sort_values("eventType",ascending=True)
viajes = viajes.sort_values(by=["simulationId", "truckId", "eventTime"])

In [40]:
viajes

,eventDescription,eventTime,eventType,simulationId,truckId
12335,"(plaza del Dos de Mayo, 6, Madrid, [-3.7041862...",660,Truck departed,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL
12942,"(calle del Poeta Blas de Otero, 22, Madrid, [-...",751620,Truck arrived,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL
13113,"(calle del Poeta Blas de Otero, 22, Madrid, [-...",993000,Truck departed,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL
13524,"(calle de Valdecanillas, 59, Madrid, [-3.62356...",1475520,Truck arrived,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL
13667,"(calle de Valdecanillas, 59, Madrid, [-3.62356...",1657470,Truck departed,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL
...,...,...,...,...,...
8090,"(calle San Vidal, 24, AlcalÃ¡ de Henares, [-3.3...",3933480,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY
8218,"(calle San Vidal, 24, AlcalÃ¡ de Henares, [-3.3...",4114950,Truck departed,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY
10953,"(calle de la Comunidad de Madrid, 37, Rozas de...",7323780,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY
11177,"(calle de la Comunidad de Madrid, 37, Rozas de...",7626360,Truck departed,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY
11613,"(calle San AndrÃ©s, 21, Majadahonda, [-3.871769...",8182980,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY

In [41]:
viajes["deliverTime"] = viajes["eventTime"].diff()
viajes = viajes[viajes.eventType == "Truck arrived"]
viajes

,eventDescription,eventTime,eventType,simulationId,truckId,deliverTime
12942,"(calle del Poeta Blas de Otero, 22, Madrid, [-...",751620,Truck arrived,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,750960.0
13524,"(calle de Valdecanillas, 59, Madrid, [-3.62356...",1475520,Truck arrived,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,482520.0
13918,"(avda de la InstituciÃ³n Libre de EnseÃ±anza, 19...",1969320,Truck arrived,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,311850.0
14315,"(bulev de JosÃ© Prat, 5, Madrid, [-3.6233859044...",2508720,Truck arrived,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,418680.0
14796,"(avda de la Albufera, 432, Madrid, [-3.6302862...",3088320,Truck arrived,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,458820.0
...,...,...,...,...,...,...
7052,"(calle Luis Madrona, S/N, AlcalÃ¡ de Henares, [...",2697810,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,2215560.0
7505,"(calle MarquÃ©s de Alonso MartÃ­nez, 9, AlcalÃ¡ d...",3259080,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,198720.0
8090,"(calle San Vidal, 24, AlcalÃ¡ de Henares, [-3.3...",3933480,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,372420.0
10953,"(calle de la Comunidad de Madrid, 37, Rozas de...",7323780,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,3208830.0
11613,"(calle San AndrÃ©s, 21, Majadahonda, [-3.871769...",8182980,Truck arrived,fea13535-ade6-4215-96ca-dab5b4ef309b,6965XLY,556620.0

el plan del es es la estimacion y la simulacion es lo real

In [43]:
import pickle



with open('model.pkl', 'wb') as f:
Â  Â  pickle.dump(model, f)

SyntaxError: invalid non-printable character U+00A0 (2542561236.py, line 4)

### Entrenar modelos de ML

variables

In [56]:
# Suponiendo que 'planes_desanidado_x2' tiene una columna 'duration' y un orden correcto de la ruta.
planes_desanidado_x2['tiempo_viaje_acumulado'] = planes_desanidado_x2.groupby(['simulationId', 'truck_id'])['duration'].cumsum()

In [57]:
# Supongamos que la capacidad mÃ¡xima es un valor fijo (por ejemplo, 100 paquetes)
capacidad_max = 100

# Si la columna 'items' es una lista con los paquetes asignados a cada trayecto:
planes_desanidado_x2['num_paquetes'] = planes_desanidado_x2['items'].apply(lambda x: len(x) if isinstance(x, list) else 0)
planes_desanidado_x2['carga_camion'] = planes_desanidado_x2['num_paquetes'] / capacidad_max

In [58]:
# La variable 'destination' ya estÃ¡ presente
# Por ejemplo, para el primer trayecto:
destino_actual = planes_desanidado_x2.loc[0, 'destination']

In [59]:
# NÃºmero de localizaciones diferentes visitadas por cada camiÃ³n en cada simulaciÃ³n
locaciones_diferentes = planes_desanidado_x2.groupby(['simulationId', 'truck_id'])['destination'].nunique().reset_index()
locaciones_diferentes.rename(columns={'destination': 'num_localizaciones_visitadas'}, inplace=True)

In [60]:
# Contar el nÃºmero de trayectos planificados (o paradas) para cada camiÃ³n en cada simulaciÃ³n
paradas_planificadas = planes_desanidado_x2.groupby(['simulationId', 'truck_id']).size().reset_index(name='num_localizaciones_planificadas')

In [61]:
# Para una fila concreta, el tiempo estimado es simplemente:
tiempo_trayecto_actual = planes_desanidado_x2.loc[0, 'duration']

In [62]:
# Supongamos que en cada fila, 'items' es una lista de identificadores de paquete.
id_paquetes_entregados = planes_desanidado_x2.loc[0, 'items']
# O, si se entrega uno a la vez:
id_paquete_actual = id_paquetes_entregados[0] if id_paquetes_entregados else None

In [63]:
num_paquetes_entregados = len(planes_desanidado_x2.loc[0, 'items']) if isinstance(planes_desanidado_x2.loc[0, 'items'], list) else 0

In [64]:
def num_letras_distintas(sim_id):
    return len(set(sim_id))
    
planes_desanidado_x2['num_letras_sim'] = planes_desanidado_x2['simulationId'].apply(num_letras_distintas)

In [65]:
# Ejemplo:
id_camion = planes_desanidado_x2.loc[0, 'truck_id']

In [66]:
planes_desanidado_x2

,items_planes,simulationId,trucks,items,route,truck_id,destination,duration,origin,tiempo_viaje_acumulado,num_paquetes,carga_camion,num_letras_sim
2334,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,2e8d1b7b9fad4f083892d83c,614,ce6feed06bc1a9e5aff95f04,614,26,0.26,14
2335,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,f5a3aab0c10fb7c5c60f2b01,397,2e8d1b7b9fad4f083892d83c,1011,26,0.26,14
2336,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,4b5f692a806a39d1317d15d4,259,f5a3aab0c10fb7c5c60f2b01,1270,26,0.26,14
2337,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,64bba266de127a5949f52d9a,349,4b5f692a806a39d1317d15d4,1619,26,0.26,14
2338,"[{'itemId': '0', 'locationId': 'bc451e2cea161c...",007f3d08-14a7-4a93-af9e-f0d9cfbcea94,"[{'items': ['68', '69', '70', '53', '54', '55'...","[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...","[{'destination': '2e8d1b7b9fad4f083892d83c', '...",3321FBL,6942f2624e971761b7dd9208,384,64bba266de127a5949f52d9a,2003,26,0.26,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,92e059821c9ca8b3967bece4,157,fb28b93228a49e10f73abd62,2202,17,0.17,15
1257,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,1f9012c136c055e10f9ef9cb,300,92e059821c9ca8b3967bece4,2502,17,0.17,15
1258,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,0efbacc39472a86ca3de1b21,2620,1f9012c136c055e10f9ef9cb,5122,17,0.17,15
1259,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,7658997164924eab18ea6e08,472,0efbacc39472a86ca3de1b21,5594,17,0.17,15
1260,"[{'itemId': '0', 'locationId': '17d843cfd0ff57...",fea13535-ade6-4215-96ca-dab5b4ef309b,"[{'items': ['61', '62', '63', '11', '12', '13'...","[15, 44, 45, 46, 47, 22, 23, 24, 2, 3, 40, 41,...","[{'destination': '58bb022022a0e97ef0efcf46', '...",6965XLY,ce6feed06bc1a9e5aff95f04,1322,7658997164924eab18ea6e08,6916,17,0.17,15

In [68]:
# Crear un dataframe con las variables deseadas
df_features = planes_desanidado_x2.copy()

# Tiempo de viaje acumulado
df_features['tiempo_viaje_acumulado'] = df_features.groupby(['simulationId', 'truck_id'])['duration'].cumsum()

# Carga del camiÃ³n
capacidad_max = 100  # ajustar segÃºn corresponda
df_features['num_paquetes'] = df_features['items'].apply(lambda x: len(x) if isinstance(x, list) else 0)
df_features['carga_camion'] = df_features['num_paquetes'] / capacidad_max

# La localizaciÃ³n de destino ya estÃ¡ en 'destination'
# NÃºmero de localizaciones diferentes visitadas (por simulaciÃ³n y camiÃ³n)
locaciones_diferentes = df_features.groupby(['simulationId', 'truck_id'])['destination'].nunique().reset_index()
locaciones_diferentes.rename(columns={'destination': 'num_localizaciones_visitadas'}, inplace=True)
df_features = df_features.merge(locaciones_diferentes, on=['simulationId', 'truck_id'], how='left')

# NÃºmero de localizaciones planificadas en la ruta
paradas_planificadas = df_features.groupby(['simulationId', 'truck_id']).size().reset_index(name='num_localizaciones_planificadas')
df_features = df_features.merge(paradas_planificadas, on=['simulationId', 'truck_id'], how='left')

# Tiempo de viaje estimado para el trayecto actual ya estÃ¡ en 'duration'
df_features.rename(columns={'duration': 'tiempo_viaje_estimado'}, inplace=True)

# El identificador del paquete y nÃºmero de paquetes entregados se derivan de 'items'
df_features['id_paquetes'] = df_features['items']  # puede ser una lista o transformarlo a string
df_features['num_paquetes_entregados'] = df_features['items'].apply(lambda x: len(x) if isinstance(x, list) else 0)

# NÃºmero de letras distintas en el id de simulaciÃ³n
df_features['num_letras_sim'] = df_features['simulationId'].apply(num_letras_distintas)

# El identificador del camiÃ³n ya estÃ¡ en 'truck_id'
df_features[['simulationId', 'truck_id', 'tiempo_viaje_acumulado', 'carga_camion', 'destination','num_localizaciones_visitadas', 'num_localizaciones_planificadas', 'tiempo_viaje_estimado','id_paquetes', 'num_paquetes_entregados', 'num_letras_sim']].head()

,simulationId,truck_id,tiempo_viaje_acumulado,carga_camion,destination,num_localizaciones_visitadas,num_localizaciones_planificadas,tiempo_viaje_estimado,id_paquetes,num_paquetes_entregados,num_letras_sim
0,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,614,0.26,2e8d1b7b9fad4f083892d83c,15,15,614,"[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...",26,14
1,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,1011,0.26,f5a3aab0c10fb7c5c60f2b01,15,15,397,"[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...",26,14
2,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,1270,0.26,4b5f692a806a39d1317d15d4,15,15,259,"[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...",26,14
3,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,1619,0.26,64bba266de127a5949f52d9a,15,15,349,"[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...",26,14
4,007f3d08-14a7-4a93-af9e-f0d9cfbcea94,3321FBL,2003,0.26,6942f2624e971761b7dd9208,15,15,384,"[78, 79, 50, 51, 52, 23, 21, 58, 59, 60, 61, 4...",26,14

In [74]:
import numpy as np
variables_iniciales = ['tiempo_viaje_acumulado', 'carga_camion', 'num_localizaciones_visitadas',
                       'num_localizaciones_planificadas', 'tiempo_viaje_estimado',
                       'num_paquetes_entregados', 'num_letras_sim']

# Calcular la matriz de correlaciÃ³n
corr_matrix = df_features[variables_iniciales].corr().abs()

# Seleccionar la parte superior de la matriz de correlaciÃ³n (triangular) para evitar duplicados
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Mostrar variables altamente correlacionadas (umbral, por ejemplo, 0.9)
umbral = 0.9
print("Variables altamente correlacionadas (coeficiente > {}):".format(umbral))
print(upper_tri[upper_tri > umbral].dropna(how='all', axis=0))

# Suponiendo que encontramos que 'tiempo_viaje_estimado' y 'tiempo_viaje_acumulado' estÃ¡n muy correlacionados,
# podrÃ­amos decidir conservar solo 'tiempo_viaje_estimado'.
variables_seleccionadas = ['tiempo_viaje_estimado', 'carga_camion', 'num_localizaciones_visitadas',
                           'num_localizaciones_planificadas', 'num_paquetes_entregados', 'num_letras_sim']

# TambiÃ©n se pueden crear variables dummy si se decide incluir la localizaciÃ³n de destino
if 'destination' in df_features.columns:
    destination_dummies = pd.get_dummies(df_features['destination'], prefix='dest', drop_first=True)
    df_features_model = pd.concat([df_features[variables_seleccionadas], destination_dummies], axis=1)
else:
    df_features_model = df_features[variables_seleccionadas]

# Ahora df_features_model contiene las variables de entrada para el modelo de ML.
print("Variables de entrada para el modelo:")
df_features_model.head()

Variables altamente correlacionadas (coeficiente > 0.9):
                                 tiempo_viaje_acumulado  carga_camion  \
carga_camion                                        NaN           NaN
num_localizaciones_visitadas                        NaN           NaN
num_localizaciones_planificadas                     NaN           NaN

                                 num_localizaciones_visitadas  \
carga_camion                                         0.932276
num_localizaciones_visitadas                              NaN
num_localizaciones_planificadas                           NaN

                                 num_localizaciones_planificadas  \
carga_camion                                            0.932276
num_localizaciones_visitadas                            1.000000
num_localizaciones_planificadas                              NaN

                                 tiempo_viaje_estimado  \
carga_camion                                       NaN
num_localizaciones_visitadas                       NaN
num_localizaciones_planificadas                    NaN

                                 num_paquetes_entregados  num_letras_sim
carga_camion                                    1.000000             NaN
num_localizaciones_visitadas                    0.932276             NaN
num_localizaciones_planificadas                 0.932276             NaN
Variables de entrada para el modelo:

,tiempo_viaje_estimado,carga_camion,num_localizaciones_visitadas,num_localizaciones_planificadas,num_paquetes_entregados,num_letras_sim,dest_00ff35c9e139e54ac2cd8d5d,dest_0109fc10152c17acb1b7385e,dest_010a38206989928048905335,dest_019899f48d82e0607d27aed2,...,dest_feb46df82ebd44a356ebeb50,dest_fec82296fab33ff598504aed,dest_feced6113c28ab67ed0bbd38,dest_fee73d0c9dd94afa9a393e87,dest_ff8fce5fe3ed339425c1ddac,dest_ffa5f7ccb8bc3bafabdb1135,dest_ffcf4e1b98451c0a06931a47,dest_ffd8dc57f22920723c82bc01,dest_ffe1940618db72629fba0bb6,dest_fff05cef104e52f22448f283
0,614,0.26,15,15,26,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,397,0.26,15,15,26,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,259,0.26,15,15,26,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,349,0.26,15,15,26,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,384,0.26,15,15,26,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [76]:
import pandas as pd
import numpy as np

# Supongamos que ya tienes el dataframe 'df_features_model' con las variables:
# - tiempo_viaje_estimado
# - carga_camion
# - num_localizaciones_visitadas
# - num_localizaciones_planificadas
# - num_paquetes_entregados
# - num_letras_sim
# - Variables dummy para 'destination' (por ejemplo, columnas que empiezan con 'dest_')
# - (Adicionalmente pueden existir identificadores como simulationId o truck_id que descartaremos)

# Paso 1: Seleccionar las variables base (descartamos identificadores)
variables_base = ['tiempo_viaje_estimado', 'carga_camion', 'num_localizaciones_visitadas',
                  'num_localizaciones_planificadas', 'num_paquetes_entregados', 'num_letras_sim']

# Paso 2: Reducir la dimensionalidad de las dummies de 'destination'
# Asumimos que las variables dummy tienen un prefijo, por ejemplo, 'dest_'
dummy_cols = [col for col in df_features_model.columns if col.startswith('dest_')]

# Contar la frecuencia total de cada dummy (la suma de la columna indica cuÃ¡ntas veces aparece esa categorÃ­a)
dummy_frecuencias = df_features_model[dummy_cols].sum().sort_values(ascending=False)
# Seleccionar, por ejemplo, las 10 categorÃ­as principales
top_dummy_cols = dummy_frecuencias.head(10).index.tolist()

# Combinar las variables base con las dummies seleccionadas
variables_model = variables_base + top_dummy_cols

# Construir el dataframe final de features
df_model = df_features_model[variables_model]

# Paso 3: Eliminar variables altamente correlacionadas entre las variables numÃ©ricas
# Solo consideramos las variables numÃ©ricas (excluyendo las dummies de destino, que son 0/1)
df_numericas = df_model[variables_base]

# Calcular la matriz de correlaciÃ³n absoluta
corr_matrix = df_numericas.corr().abs()

# Tomamos la parte superior (triangular) para identificar pares redundantes
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Establecer un umbral (por ejemplo, 0.9) para considerar alta correlaciÃ³n
umbral = 0.9

# Identificar las variables que se pueden eliminar (si tienen alta correlaciÃ³n con alguna otra)
variables_a_eliminar = [col for col in upper_tri.columns if any(upper_tri[col] > umbral)]
print("Variables numÃ©ricas a eliminar por alta correlaciÃ³n:", variables_a_eliminar)

# Crear el conjunto final de variables numÃ©ricas seleccionadas (descartar las variables redundantes)
variables_numericas_final = [var for var in variables_base if var not in variables_a_eliminar]

# Combinar con las dummies seleccionadas (estas no se consideran para la correlaciÃ³n ya que son binarias)
variables_final = variables_numericas_final + top_dummy_cols
print("Variables finales seleccionadas para el modelo:")
print(variables_final)

# Dataframe final para el modelo
df_model_final = df_model[variables_final]
print("\nPrimeras filas del dataset final para el modelo:")
df_model_final.head()

Variables numÃ©ricas a eliminar por alta correlaciÃ³n: ['num_localizaciones_visitadas', 'num_localizaciones_planificadas', 'num_paquetes_entregados']
Variables finales seleccionadas para el modelo:
['tiempo_viaje_estimado', 'carga_camion', 'num_letras_sim', 'dest_ce6feed06bc1a9e5aff95f04', 'dest_855b071bf897e2265abd7096', 'dest_94a4877361dfc7ba1b87cab4', 'dest_a639f83692337484fc4d432b', 'dest_31d46e31a77f056cf15f5e18', 'dest_c5b8d238912c89e30916e92b', 'dest_5a16559b09cb7c6f37c4e733', 'dest_502e8d84cab29327b2793d0c', 'dest_3163705e2e4c79485482b907', 'dest_18a34a3417da4a62f4734336']

Primeras filas del dataset final para el modelo:

,tiempo_viaje_estimado,carga_camion,num_letras_sim,dest_ce6feed06bc1a9e5aff95f04,dest_855b071bf897e2265abd7096,dest_94a4877361dfc7ba1b87cab4,dest_a639f83692337484fc4d432b,dest_31d46e31a77f056cf15f5e18,dest_c5b8d238912c89e30916e92b,dest_5a16559b09cb7c6f37c4e733,dest_502e8d84cab29327b2793d0c,dest_3163705e2e4c79485482b907,dest_18a34a3417da4a62f4734336
0,614,0.26,14,0,0,0,0,0,0,0,0,0,0
1,397,0.26,14,0,0,0,0,0,0,0,0,0,0
2,259,0.26,14,0,0,0,0,0,0,0,0,0,0
3,349,0.26,14,0,0,0,0,0,0,0,0,0,0
4,384,0.26,14,0,0,0,0,0,0,0,0,0,0